namespace OhioEdiParser.CodeSets;

public static class LivingArrangementCodes
{
    private static readonly Dictionary<string, string> Codes = new()
    {
        ["01"] = "Independent (Home/Apart/Trlr)",
        ["02"] = "Public Institution",
        ["03"] = "Adult Family Home",
        ["04"] = "Adult Care Facility",
        ["05"] = "Mental Health Residential",
        ["06"] = "ICF/IID",
        ["07"] = "MR/DD Residential",
        ["08"] = "Personal Care",
        ["09"] = "Nursing Home/Group Home",
        ["10"] = "Nursing Home (LTCF)",
        ["11"] = "Shared Living",
        ["12"] = "Supported Living",
        ["13"] = "Homeless",
        ["14"] = "Correctional Institution",
        ["15"] = "Jail",
        ["16"] = "Home & Community Based Waiver",
        ["17"] = "Community Based ICDS",
        ["18"] = "Institutional ICDS",
        ["19"] = "Residential Care Facility",
        ["20"] = "Nursing Facility Level of Care",
        ["21"] = "PACE",
        ["22"] = "Death",
        ["23"] = "Under 21 Years, Out of Home",
        ["24"] = "Under 21 Years, In Custody",
        ["25"] = "Adoption Assistance",
        ["26"] = "Hospice",
        ["27"] = "Hospital",
        ["28"] = "Rehabilitation Center",
        ["29"] = "Crisis Stabilization",
        ["30"] = "Therapeutic Foster Care",
        ["31"] = "Group Home Youth",
        ["32"] = "Residential Treatment Youth",
        ["33"] = "Independent Living Youth",
        ["34"] = "Semi-Independent Living",
        ["35"] = "Supported Employment",
        ["36"] = "Day Habilitation",
        ["37"] = "Vocational",
        ["38"] = "Sheltered Workshop",
        ["39"] = "Community Employment",
        ["40"] = "Day Treatment",
        ["41"] = "Respite Care",
        ["42"] = "Camp",
        ["43"] = "School-Based",
        ["44"] = "After-School",
        ["45"] = "Summer Program",
        ["46"] = "Pre-Vocational",
        ["47"] = "Transitional Living",
        ["48"] = "Home Health",
        ["49"] = "Private Duty Nursing",
        ["50"] = "Home Medical Equipment",
        ["51"] = "Transportation",
        ["52"] = "Dental",
        ["53"] = "Vision",
        ["54"] = "Hearing",
        ["55"] = "Behavioral Health",
        ["56"] = "Substance Use Treatment",
        ["57"] = "Physical Therapy",
        ["58"] = "Occupational Therapy",
        ["59"] = "Speech Therapy",
        ["60"] = "Dietary/Nutrition",
        ["61"] = "Pharmacy",
        ["62"] = "Lab",
        ["63"] = "Radiology",
        ["64"] = "Emergency Room",
        ["65"] = "Urgent Care",
        ["66"] = "Outpatient Surgery",
        ["67"] = "Inpatient",
        ["68"] = "Observation",
        ["69"] = "Partial Hospitalization",
        ["70"] = "IOP",
        ["71"] = "Residential SUD",
        ["72"] = "Detox",
        ["73"] = "MAT",
        ["74"] = "Peer Support",
        ["FC"] = "Foster Care",
        ["KG"] = "Kinship Guardianship Assistance Program",
        ["SA"] = "Subsidized Adoption",
        ["XX"] = "Unknown"
    };

    public static string? GetDescription(string code) => Codes.GetValueOrDefault(code);
    public static bool IsKnown(string code) => Codes.ContainsKey(code);

    public static readonly HashSet<string> InstitutionalCodes = new()
    {
        "02", "09", "10", "19", "20", "26", "27"
    };
}
